use_frameworks!

platform :ios, '11.0'

target 'XDScan_Example' do
  pod 'XDScan', :path => '../'

  target 'XDScan_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
